# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'garvis_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Leo(object):
    def setupUi(self, Leo):
        Leo.setObjectName("Leo")
        Leo.resize(1366, 768)
        Leo.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Leo GUI/7gQj.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Leo.setWindowIcon(icon)
        Leo.setStyleSheet("background-color:black;")
        Leo.setDocumentMode(True)
        self.centralwidget = QtWidgets.QWidget(Leo)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(620, 550, 131, 121))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Leo GUI/fxVE.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1050, 490, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("color: white;\n"
"font-size: 22px;\n"
"font-weight: bold;\n"
"background-color: rgb(9, 170, 1);\n"
"padding: 5px;\n"
"cursor:pointer;")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1170, 490, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_2.setAutoFillBackground(False)
        self.pushButton_2.setStyleSheet("color: white;\n"
"font-size: 22px;\n"
"font-weight: bold;\n"
"padding: 5px;\n"
"cursor:pointer;\n"
"background-color: rgb(255, 0, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(970, 200, 331, 211))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("Leo GUI/—Pngtree—technology border_5645017.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(1020, 250, 171, 31))
        self.textBrowser.setStyleSheet("background:transparent;\n"
"color:#fff;\n"
"border:none;")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(1150, 260, 111, 31))
        self.textBrowser_2.setStyleSheet("background:transparent;\n"
"color:#fff;\n"
"border:none;")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_5.setGeometry(QtCore.QRect(1230, 70, 51, 31))
        self.textBrowser_5.setStyleSheet("background:transparent;\n"
"color:#fff;\n"
"border:none;")
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(1140, 100, 181, 31))
        self.textBrowser_3.setStyleSheet("background:transparent;\n"
"color:#fff;\n"
"border:none;")
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(70, 170, 371, 311))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("Leo GUI/MImN.gif"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(1190, 70, 61, 15))
        self.progressBar.setProperty("value", 70)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_4.setGeometry(QtCore.QRect(1050, 330, 241, 31))
        self.textBrowser_4.setStyleSheet("background:transparent;\n"
"color:#fff;\n"
"border:none;")
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -10, 1371, 761))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Leo GUI/pngwing.com (1).png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(460, 80, 511, 271))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("Leo GUI/loading.gif"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(460, 270, 511, 271))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("Leo GUI/J4o.gif"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(470, 110, 601, 61))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit.setFont(font)
        self.textEdit.setAutoFillBackground(False)
        self.textEdit.setStyleSheet("background:transparent;\n"
"color:#fff;\n"
"border:none;")
        self.textEdit.setObjectName("textEdit")
        self.label.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.label_4.raise_()
        self.label_2.raise_()
        self.textBrowser_3.raise_()
        self.progressBar.raise_()
        self.textBrowser_5.raise_()
        self.label_3.raise_()
        self.textBrowser_2.raise_()
        self.textBrowser.raise_()
        self.textBrowser_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.textEdit.raise_()
        Leo.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Leo)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1366, 21))
        self.menubar.setObjectName("menubar")
        Leo.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Leo)
        self.statusbar.setObjectName("statusbar")
        Leo.setStatusBar(self.statusbar)

        self.retranslateUi(Leo)
        QtCore.QMetaObject.connectSlotsByName(Leo)

    def retranslateUi(self, Leo):
        _translate = QtCore.QCoreApplication.translate
        Leo.setWindowTitle(_translate("Leo", "Leo | Personal voice assistant - By Bhuwan Acharya "))
        Leo.setToolTip(_translate("Leo", "<html><head/><body><p>Leo - Developed By Bhuwan Acharya</p></body></html>"))
        self.pushButton.setText(_translate("Leo", "Run Leo"))
        self.pushButton_2.setText(_translate("Leo", "Exit"))
        self.textBrowser.setHtml(_translate("Leo", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">2023 / 10 / 12</span></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("Leo", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">18 : 37 : 45 PM</span></p></body></html>"))
        self.textBrowser_5.setHtml(_translate("Leo", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">99%</span></p></body></html>"))
        self.textBrowser_3.setHtml(_translate("Leo", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Nepal</p></body></html>"))
        self.textBrowser_4.setHtml(_translate("Leo", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">Dhangadhi (Temperature) : 23° C</span></p></body></html>"))
        self.textEdit.setHtml(_translate("Leo", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Yu Gothic UI Semibold\'; font-size:10pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Leo = QtWidgets.QMainWindow()
    ui = Ui_Leo()
    ui.setupUi(Leo)
    Leo.show()
    sys.exit(app.exec_())
